name: CI

on:
  push:
    branches:
      - master

env:
  MOON_DEBUG: 'true'
  PROTO_DEBUG: 'true'

jobs:
  ci:
    name: CI
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      # https://moonrepo.dev/docs/guides/ci
      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@8794f0318b9df4a43a5ddc23cefd16f595b423dd # v0
        with:
          auto-install: true

      - name: CI-check the whole repository targets actions
        run: 'moon ci --color'

      - name: Collect/retrospect on Moon's CI Summaries
        uses: appthrust/moon-ci-retrospect@631a1e667f96e8ca893eab69f03e425f7fbfdc2b # latest release
        if: success() || failure()
