name: PR

on:
  pull_request:

env:
  MOON_DEBUG: 'true'
  PROTO_DEBUG: 'true'

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@8794f0318b9df4a43a5ddc23cefd16f595b423dd # v0
        with:
          auto-install: true

      - name: CI
        run: moon ci --color

      - name: Report action outcome to PR
        uses: moonrepo/run-report-action@bfb317b1a2fd5b879d7c14d6d7af6360178fd879 # v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.PR_GITHUB_TOKEN }}

      - name: Collect/retrospect on Moon's CI Summaries
        uses: appthrust/moon-ci-retrospect@631a1e667f96e8ca893eab69f03e425f7fbfdc2b # latest release
        if: success() || failure()
